export const hotData = {
  resultList: [
    {
      id: 1,
      name: '1[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 0,
      like: true,
      cart: true,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 2,
      name: '2[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 1,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 3,
      name: '3[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 2,
      like: true,
      cart: true,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 4,
      name: '4[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 3,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 5,
      name: '5[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 4,
      like: true,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 6,
      name: '6[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 7,
      name: '7[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: true,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 8,
      name: '8[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 9,
      name: '9[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 0,
      like: true,
      cart: true,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 10,
      name: '10[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 11,
      name: '11[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 1,
      like: true,
      cart: true,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 12,
      name: '12[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 2,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 13,
      name: '13[마지막기회] 신소재 앵무새 집',
      price: '82500.000',
      stock: 1,
      like: true,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 14,
      name: '14[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 2,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 15,
      name: '15[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: true,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
    {
      id: 16,
      name: '16[마지막기회] 신소재 고슴도치 집',
      price: '83100.000',
      stock: 0,
      like: false,
      cart: false,
      imgSrc: 'https://picsum.photos/200/300?random=1',
    },
  ],
  page: 1,
  pageSize: 2,
  totalCount: 90,
  totalPageCount: 45,
  numberOfElements: 2,
};
